### ISSUE TITLE
various `sky-list-*` components don't migrate out of the box during skyux 3 upgrade for a skyux-lib

### ISSUE THREAD

**Issue by alex-vaky** [blackbaud/skyux-sdk-builder-plugin-migrate#30] opened 2019-03-15 16:51 UTC
I'm still troubleshooting this myself, but I figured I'd open the ticket now so it's logged and can be referenced by others.
```
 0=: 'sky-list-toolbar-item' is not a known element:
1. If 'sky-list-toolbar-item' is an Angular component, then verify that it is part of this module.
2. If 'sky-list-toolbar-item' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("Fields]="{fieldSelector:'enqueuedTimeUtc', descending:false}">
        <sky-list-toolbar>
          [ERROR ->]<sky-list-toolbar-item location="right">
            <ng-template>
              <span class="topic-p")

: Can't bind to 'isSortable' since it isn't a known property of 'sky-grid-column'.
1. If 'sky-grid-column' is an Angular component and it has 'isSortable' input, then verify that it is part of this module.
2. If 'sky-grid-column' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("st-toolbar>
        <sky-list-view-grid>
          <sky-grid-column width="50" field="context-menu" [ERROR ->][isSortable]="false" [template]="contextMenuButtonTemplate" locked="true"></sky-grid-column>
        ")

: Can't bind to 'template' since it isn't a known property of 'sky-grid-column'.
1. If 'sky-grid-column' is an Angular component and it has 'template' input, then verify that it is part of this module.
2. If 'sky-grid-column' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("sky-list-view-grid>
          <sky-grid-column width="50" field="context-menu" [isSortable]="false" [ERROR ->][template]="contextMenuButtonTemplate" locked="true"></sky-grid-column>
          <sky-grid-column cl")

: 'sky-grid-column' is not a known element:
1. If 'sky-grid-column' is an Angular component, then verify that it is part of this module.
2. If 'sky-grid-column' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        </sky-list-toolbar>
        <sky-list-view-grid>
          [ERROR ->]<sky-grid-column width="50" field="context-menu" [isSortable]="false" [template]="contextMenuButtonTe")

: 'sky-list-view-grid' is not a known element:
1. If 'sky-list-view-grid' is an Angular component, then verify that it is part of this module.
2. If 'sky-list-view-grid' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
          </sky-list-toolbar-item>
        </sky-list-toolbar>
        [ERROR ->]<sky-list-view-grid>
          <sky-grid-column width="50" field="context-menu" [isSortable]="false" ")
```

**Comment by alex-vaky** [comment] 2019-03-15 16:56
I was able to resolve these issues manually by including the follow import statements and adding those modules to my existing `imports` set: 
```
import { ..., SkyListToolbarModule } from '@skyux/list-builder';
import { SkyListViewGridModule } from '@skyux/list-builder-view-grids';
import { SkyGridModule } from '@skyux/grids';
...
  imports: [
    ...
    SkyListToolbarModule,
    SkyGridModule,
    SkyListViewGridModule,
    ...
  ],
... 
```
I would hope these additions could be added to the migration process automatically as I assume many apps will be using lists in a similar manner

**Comment by Blackbaud-AlexKingman** [comment] 2019-03-26 18:25
Thanks for filing this @Blackbaud-AlexanderVaky . For your particular migration scenario, it looks like the three modules in question (`SkyListToolbarModule`, `SkyGridModule`, and `SkyListViewGridModule`) were never included in the component's module to begin with. For reference, See the commit to `DlqMessageListModule` [here](https://blackbaud.visualstudio.com/Products/_git/skyux-lib-dlq-management/commit/ef2a9f47c5d257e61aa9cea3c2aa99fd8eb5046e?refName=refs%2Fheads%2Fmaster&_a=compare&path=%2Fsrc%2Fapp%2Fpublic%2Fsrc%2Fmodules%2Fdlq-message-list%2Fdlq-message-list.module.ts).

This is certainly strange, as it should have needed those 3 modules imported to work properly before. We're wondering if there was some automatic importing going on behind the scenes with older versions of angular/builder. It looks like the migration tool has just shed light on an issue that was already there.

To confirm these particular modules work as expected, we ran a test scenario where we replicated your app "pre-migration". Then, we added the three modules above to the `DlqMessageListModule` with imports to the old SKY UX 2 paths. We ran the migration tool and can confirm that all the new modules were updated the new paths correctly (including the three above).

For these particular modules, we believe the migration tool is working as intended. I'm going to close the issue for now, but please feel free to re-open it if you feel there's still an issue. Thanks!

**Closed as completed by Blackbaud-AlexKingman** 2019-03-26 18:25 UTC
Labels: From: Consumer, Severity: High, Type: Bug
